# Generated by Django 5.0.6 on 2024-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('mid_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('dostup', models.BooleanField(default=False, verbose_name='Администратор')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователь',
            },
        ),
    ]
