# Generated by Django 5.0.6 on 2024-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_login_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pas',
            field=models.CharField(default=2, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=100, verbose_name='Логин'),
        ),
    ]
