# Generated by Django 5.0.6 on 2024-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Znaniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otl_koleb', models.IntegerField(verbose_name='Отклонение и колебание напряжения')),
                ('nes', models.IntegerField(verbose_name='Нессиметрия')),
                ('sin', models.IntegerField(verbose_name='Несинусоидальность')),
                ('otl_chast', models.IntegerField(verbose_name='Отклонение частоты')),
                ('pomehi', models.IntegerField(verbose_name='Электромагнитные помехи')),
            ],
        ),
    ]
