# Generated by Django 5.0.6 on 2024-06-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='znaniya',
            options={'verbose_name': 'Правило', 'verbose_name_plural': 'Правила'},
        ),
        migrations.AlterField(
            model_name='znaniya',
            name='nes',
            field=models.FloatField(verbose_name='Нессиметрия'),
        ),
        migrations.AlterField(
            model_name='znaniya',
            name='otl_chast',
            field=models.FloatField(verbose_name='Отклонение частоты'),
        ),
        migrations.AlterField(
            model_name='znaniya',
            name='otl_koleb',
            field=models.FloatField(verbose_name='Отклонение и колебание напряжения'),
        ),
        migrations.AlterField(
            model_name='znaniya',
            name='pomehi',
            field=models.FloatField(verbose_name='Электромагнитные помехи'),
        ),
        migrations.AlterField(
            model_name='znaniya',
            name='sin',
            field=models.FloatField(verbose_name='Несинусоидальность'),
        ),
    ]
