# Generated by Django 5.0.6 on 2024-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_znaniya_vid_eto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='znaniya',
            name='vid_eto',
            field=models.CharField(choices=[('Синхронные двигатели', 'Синхронные двигатели'), ('Асинхронные двигатели', 'Асинхронные двигатели'), ('Вентильные двигатель-генераторы', 'Вентильные двигатель-генераторы')], max_length=100, verbose_name='Вид ЭТО'),
        ),
    ]
