# Generated by Django 5.0.6 on 2024-06-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_znaniya_vid_eto'),
    ]

    operations = [
        migrations.AddField(
            model_name='znaniya',
            name='vid_metod',
            field=models.CharField(choices=[('Метод стандартных отклонений', 'Метод стандартных отклонений'), ('Метод медианы Кемени', 'Метод медианы Кемени')], default=1, max_length=100, verbose_name='Вид метода'),
            preserve_default=False,
        ),
    ]
