# Generated by Django 5.0.6 on 2024-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dvigateli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=100, verbose_name='Название модели')),
                ('vid_eto', models.CharField(default='', max_length=100, verbose_name='Вид ЭТО')),
                ('tip', models.CharField(default='', max_length=100, verbose_name='Тип параметров')),
            ],
        ),
    ]
