# Generated by Django 5.0.6 on 2024-05-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dvigateli',
            options={'verbose_name': 'Двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
        migrations.RemoveField(
            model_name='dvigateli',
            name='tip',
        ),
        migrations.AddField(
            model_name='dvigateli',
            name='tip_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvigateli',
            name='tip_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dvigateli',
            name='tip_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dvigateli',
            name='vid_eto',
            field=models.CharField(choices=[('Синхронный двигатель', 'Синхронный двигатель'), ('Асинхронный двигатель', 'Асинхронный двигатель'), ('Вентильный двигатель-генератор', 'Вентильный двигатель-генератор')], max_length=100, verbose_name='Вид ЭТО'),
        ),
    ]
