# Generated by Django 5.0.6 on 2024-05-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eto', '0002_alter_dvigateli_options_remove_dvigateli_tip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvigateli',
            name='tip_1',
            field=models.BooleanField(default=False, verbose_name='Основные'),
        ),
        migrations.AlterField(
            model_name='dvigateli',
            name='tip_2',
            field=models.BooleanField(default=False, verbose_name='Дополнительные'),
        ),
        migrations.AlterField(
            model_name='dvigateli',
            name='tip_3',
            field=models.BooleanField(default=False, verbose_name='Вспомогательные'),
        ),
    ]
