# Generated by Django 5.0.6 on 2024-06-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eto', '0004_dvigateli_chast_dvigateli_napr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvigateli',
            name='pasport',
            field=models.FileField(default=1, upload_to='', verbose_name='Паспорт'),
            preserve_default=False,
        ),
    ]
