# Generated by Django 5.0.6 on 2024-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eto', '0005_dvigateli_pasport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dvigateli',
            name='pasport',
        ),
    ]
